version: 2.1
orbs:
  gradle: circleci/gradle@2.0.1
  aws-ecr: circleci/aws-ecr@6.0.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
        account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
        repo: "${AWS_RESOURCE_NAME_PREFIX}"
        region: ${AWS_DEFAULT_REGION}
        tag: "latest"
